# Generated by Django 3.2 on 2021-04-24 23:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tweet_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Like Count'),
        ),
    ]
