# Generated by Django 3.2 on 2021-05-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_tweet_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='like_count'),
        ),
    ]
