# Generated by Django 3.2 on 2021-04-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='body',
            field=models.CharField(db_index=True, default='', max_length=140, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='Name'),
        ),
        migrations.AlterModelTable(
            name='tweet',
            table='twitter_tweet',
        ),
    ]
