# Generated by Django 3.2 on 2021-04-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210424_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.CharField(db_index=True, default='', max_length=140, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='like_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='like_count'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='name'),
        ),
    ]
