# Generated by Django 3.2 on 2021-06-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tweet_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='like_count',
        ),
    ]
