# Generated by Django 3.2 on 2021-06-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_tweet_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=30, verbose_name='name'),
        ),
    ]
