# Generated by Django 3.2 on 2021-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210601_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
