# Generated by Django 3.2.7 on 2023-01-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_tweet_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.CharField(blank=True, db_index=True, default='', max_length=140, null=True, verbose_name='body'),
        ),
    ]
