# Generated by Django 3.2.7 on 2023-01-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_tweet_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=60, verbose_name='name'),
        ),
    ]
